In [1]:
# Numpy

In [2]:
import numpy as np

In [4]:
np.ones(10, dtype = 'int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
x = np.ones(20, dtype = int)

In [7]:
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
len(x)

20

In [9]:
sum(x)

20

In [10]:
type(x)

numpy.ndarray

In [11]:
x = np.ones(shape = (3,3))

In [12]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
x = np.ones(shape=(3,3),dtype=int)

In [16]:
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
x.size

9

In [18]:
x.nbytes?

In [47]:
x.shape

(3, 3)

In [48]:
x.nbytes

72

In [49]:
x.itemsize

8

In [23]:
y = 20

In [24]:
y.bit_length()

5

In [29]:
l1 = [i for i in range(10)]

In [30]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
l1.shape()

AttributeError: 'list' object has no attribute 'shape'

In [32]:
# so in python we can't get shape in list. 

# numpy we can get more number of methods like shape, reshape, etc

In [33]:
l2 = np.array([l1])

In [34]:
l2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
# now we incorporated l1(list) inside l2(numpy)

In [36]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
l2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
l3 = np.shape(l2)

In [43]:
l3

(1, 10)

In [44]:
l4 = np.shape(l1)

In [45]:
l4

(10,)

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.zeros((10),dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
x=np.zeros((10),dtype=int)

In [54]:
x.ndim

1

In [55]:
x=np.zeros((4,4),dtype=int)

In [56]:
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [57]:
veg=["kathiri","vendai","pagar"]
fruits=["Apple","orange","grapes","Annachi"]

In [58]:
veg.extend(fruits)

In [59]:
veg

['kathiri', 'vendai', 'pagar', 'Apple', 'orange', 'grapes', 'Annachi']

In [60]:
type(veg)

list

In [61]:
np.array(veg)

array(['kathiri', 'vendai', 'pagar', 'Apple', 'orange', 'grapes',
       'Annachi'], dtype='<U7')

In [62]:
type(veg)

list

In [63]:
l1 = [i for i in range(10)]

In [67]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
type(l1)

list

In [69]:
np.array(l1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
l2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [72]:
l2*10

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [73]:
x=np.zeros((40,40),dtype=int)

In [74]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [75]:
x.shape

(40, 40)

In [76]:
x.itemsize

8

In [77]:
x.nbytes

12800

In [78]:
x=np.linspace(0,1,10000000)

In [79]:
len(x)

10000000

In [84]:
sum(x) # this is normal sum

5000000.000000023

In [85]:
np.sum(x) # this is numpy sum

5000000.000000001

In [86]:
%timeit sum(x) # this takes more time

703 ms ± 6.62 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [87]:
%timeit np.sum(x) # this takes less time

1.9 ms ± 9.55 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
