# Numpy

In [1]:
import numpy as np

In [5]:
x = np.random.randint(10, size = (5,5))

In [6]:
x

array([[0, 7, 7, 0, 9],
       [9, 5, 9, 1, 4],
       [7, 7, 5, 7, 0],
       [4, 0, 7, 6, 7],
       [3, 1, 8, 2, 6]])

# Axis

In [7]:
x.max() # Total matrix 9 is high

9

In [8]:
x.min() # Total matrix 0 is low

0

In [9]:
x.max(axis = 0) # In each column, max value is returned

array([9, 7, 9, 7, 9])

In [10]:
x.max(axis = 1) # In each row, max value is returned

array([9, 9, 7, 7, 8])

In [11]:
x.min(axis = 0) # In each column, min value is returned

array([0, 0, 5, 0, 0])

In [12]:
x.min(axis = 1) # In each row, min value is returned

array([0, 1, 0, 0, 1])

# Arithmetic Operations

In [13]:
x = np.random.randint(12, size = (5,4))

In [14]:
x

array([[ 9, 11,  8,  8],
       [ 1, 10,  9,  4],
       [ 3,  8,  5,  3],
       [ 0,  6,  9,  2],
       [ 3,  0,  4,  4]])

In [15]:
y = np.random.randint(12, size = (5,4))

In [16]:
y

array([[ 0,  4,  6,  5],
       [ 1,  9,  1,  3],
       [ 6,  5,  5, 10],
       [ 7,  9,  3,  0],
       [10,  2,  0, 10]])

In [17]:
x + y # basic python operation

array([[ 9, 15, 14, 13],
       [ 2, 19, 10,  7],
       [ 9, 13, 10, 13],
       [ 7, 15, 12,  2],
       [13,  2,  4, 14]])

In [18]:
x - y # basic python operation

array([[ 9,  7,  2,  3],
       [ 0,  1,  8,  1],
       [-3,  3,  0, -7],
       [-7, -3,  6,  2],
       [-7, -2,  4, -6]])

In [19]:
x * y  # basic python operation

array([[ 0, 44, 48, 40],
       [ 1, 90,  9, 12],
       [18, 40, 25, 30],
       [ 0, 54, 27,  0],
       [30,  0,  0, 40]])

In [20]:
x // y #  basic python operation

/var/folders/5f/zvvxs6012zn4htwxbbkh2mvh0000gn/T/ipykernel_1466/2460002147.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  x // y


array([[0, 2, 1, 1],
       [1, 1, 9, 1],
       [0, 1, 1, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 0]])

In [21]:
x / y #  basic python operation

/var/folders/5f/zvvxs6012zn4htwxbbkh2mvh0000gn/T/ipykernel_1466/3016948717.py:1: RuntimeWarning: divide by zero encountered in true_divide
  x / y


array([[       inf, 2.75      , 1.33333333, 1.6       ],
       [1.        , 1.11111111, 9.        , 1.33333333],
       [0.5       , 1.6       , 1.        , 0.3       ],
       [0.        , 0.66666667, 3.        ,        inf],
       [0.3       , 0.        ,        inf, 0.4       ]])

In [22]:
x ** 3 #  basic python operation

array([[ 729, 1331,  512,  512],
       [   1, 1000,  729,   64],
       [  27,  512,  125,   27],
       [   0,  216,  729,    8],
       [  27,    0,   64,   64]])

In [23]:
x % 2 #  basic python operation

array([[1, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0]])

In [26]:
np.add(x,y) # using numpy operations

array([[ 9, 15, 14, 13],
       [ 2, 19, 10,  7],
       [ 9, 13, 10, 13],
       [ 7, 15, 12,  2],
       [13,  2,  4, 14]])

In [27]:
np.subtract(x,y) # using numpy operations

array([[ 9,  7,  2,  3],
       [ 0,  1,  8,  1],
       [-3,  3,  0, -7],
       [-7, -3,  6,  2],
       [-7, -2,  4, -6]])

In [28]:
np.divide(x,y) # using numpy operations

/var/folders/5f/zvvxs6012zn4htwxbbkh2mvh0000gn/T/ipykernel_1466/430945158.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(x,y)


array([[       inf, 2.75      , 1.33333333, 1.6       ],
       [1.        , 1.11111111, 9.        , 1.33333333],
       [0.5       , 1.6       , 1.        , 0.3       ],
       [0.        , 0.66666667, 3.        ,        inf],
       [0.3       , 0.        ,        inf, 0.4       ]])

In [29]:
np.multiply(x,y) # using numpy operations

array([[ 0, 44, 48, 40],
       [ 1, 90,  9, 12],
       [18, 40, 25, 30],
       [ 0, 54, 27,  0],
       [30,  0,  0, 40]])

In [30]:
np.mod(x,y) # using numpy operations

/var/folders/5f/zvvxs6012zn4htwxbbkh2mvh0000gn/T/ipykernel_1466/965914413.py:1: RuntimeWarning: divide by zero encountered in remainder
  np.mod(x,y)


array([[0, 3, 2, 3],
       [0, 1, 0, 1],
       [3, 3, 0, 3],
       [0, 6, 0, 0],
       [3, 0, 0, 4]])

# Relational Operations

In [24]:
x

array([[ 9, 11,  8,  8],
       [ 1, 10,  9,  4],
       [ 3,  8,  5,  3],
       [ 0,  6,  9,  2],
       [ 3,  0,  4,  4]])

In [31]:
y

array([[ 0,  4,  6,  5],
       [ 1,  9,  1,  3],
       [ 6,  5,  5, 10],
       [ 7,  9,  3,  0],
       [10,  2,  0, 10]])

In [25]:
x > 10

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [32]:
x > y

array([[ True,  True,  True,  True],
       [False,  True,  True,  True],
       [False,  True, False, False],
       [False, False,  True,  True],
       [False, False,  True, False]])

In [33]:
x == y

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
np.sort(x)

array([[ 8,  8,  9, 11],
       [ 1,  4,  9, 10],
       [ 3,  3,  5,  8],
       [ 0,  2,  6,  9],
       [ 0,  3,  4,  4]])

In [36]:
x = np.linspace(0,10) # 0 to 10 within the range

In [37]:
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [40]:
x = np.linspace(0,10,5) # 0 to 10 within the range of 5 elements 

In [41]:
x

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [42]:
x = np.linspace(0,10,50)

In [43]:
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [44]:
len(x)

50

In [45]:
sum(x) # this is normal python operation

250.0

In [46]:
np.sum(x) # this is numpy operation

250.0

# See we can apply the python operations in numpy arrays very easily. No need to add,sub,compare,etc each and everything. It gives the answer for the total array.

In [49]:
#-------------------------------------------------------------------------------------------------------------#

# Why numpy is better than python?
        #Bcoz numpy is faster than python

In [47]:
%timeit sum(x)

4.16 µs ± 123 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [48]:
%timeit np.sum(x)

2.37 µs ± 2.87 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
