# Dot matrix

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[2,2,3],[1,1,1]])

In [3]:
b = np.array([[1,2,3],[2,2,3],[1,1,1]])

In [4]:
a

array([[1, 2, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [5]:
b

array([[1, 2, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [6]:
np.dot(a,b)

array([[ 8,  9, 12],
       [ 9, 11, 15],
       [ 4,  5,  7]])

In [7]:
# 1st row of 'a' multiplied with 1st column of b
# 1st row of 'a' multiplied with 2nd column of b and so on

# [1,2,3] with [1,2,1] ==> 1+4+3 = 8

# [1,2,3] with [2,2,1] ==> 2+4+3 = 9

# Multiply

In [8]:
a

array([[1, 2, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [9]:
b

array([[1, 2, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [10]:
np.multiply(a,b)

array([[1, 4, 9],
       [4, 4, 9],
       [1, 1, 1]])

In [12]:
# whereas in multiply method, it directly multiplies the values of a&b

# 1*1=1, 2*2=4, 3*3=9 and so on

# * multiplication

In [11]:
a

array([[1, 2, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [12]:
b

array([[1, 2, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [13]:
a * b

array([[1, 4, 9],
       [4, 4, 9],
       [1, 1, 1]])

In [14]:
# Comparing to all these, dot matrix is different from others

# vdot

In [15]:
a = np.array([[100,200],[23,12]])

In [16]:
a

array([[100, 200],
       [ 23,  12]])

In [17]:
b = np.array([[10,20],[12,21]])

In [18]:
b

array([[10, 20],
       [12, 21]])

In [19]:
np.vdot(a,b)

5528

In [20]:
# vdot -> it is the sum of the products of matrix

In [21]:
(100*10) + (200*20) + (23*12) + (12*21) 

5528

# inner

In [22]:
a = np.array([1,2,3,4,5,6])

In [23]:
b = np.array([1,2,3,4,5,6])

In [24]:
np.inner(a,b) # sum of the products 

91

In [25]:
(1*1) + (2*2) + (3*3) + (4*4) + (5*5) + (6*6)

91

# matmul

In [26]:
np.matmul(a,b) # same like inner

91

# determinant

In [27]:
a = np.array([[1,2],[3,4]])

In [28]:
a

array([[1, 2],
       [3, 4]])

In [29]:
np.linalg.det(a)

-2.0000000000000004

In [30]:
# which means multiply in diagonal way and subtract => (1*4) - (3*2) = 4-6 => -2

# very important - always determinant should be square matrix like (2^2=4, 3^3=9, 4^4=16)

In [32]:
b = np.array([[1,2],[3,4],[5,6]])

In [33]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
np.linalg.det(b) # see it shows error.bcoz there is 6 elements and it is not square matrix

LinAlgError: Last 2 dimensions of the array must be square

In [35]:
a=np.array([[1,2,1],[3,4,1],[3,4,1]])

In [37]:
a

array([[1, 2, 1],
       [3, 4, 1],
       [3, 4, 1]])

In [36]:
np.linalg.det(a)

0.0

In [41]:
sample=np.array([['a','b','c'],['d','e','f'],['g','h','i']])

In [42]:
sample

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [43]:
# a(e*i-h*f)-b(d*i-g*f)+c(d*h-g*e)