# Numpy - append

In [1]:
# empty_like

In [2]:
import numpy as np

In [3]:
x = np.random.randint(100, size = 10)

In [4]:
x

array([34, 48, 53, 94, 75, 59, 41, 11, 15, 34])

In [5]:
y = np.empty_like(x)

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# see this method is created an empty array

In [8]:
y[:] = x # it returns all the elements in array

In [9]:
y

array([34, 48, 53, 94, 75, 59, 41, 11, 15, 34])

In [10]:
# copy

In [11]:
c = x.copy()

In [12]:
c

array([34, 48, 53, 94, 75, 59, 41, 11, 15, 34])

In [13]:
x = np.random.randint(15, size = (4,4))

In [14]:
x

array([[ 5, 12,  6,  8],
       [ 8,  5,  8,  7],
       [13, 12,  4, 12],
       [ 7, 10,  8,  6]])

In [15]:
y=np.copy(x)

In [16]:
y

array([[ 5, 12,  6,  8],
       [ 8,  5,  8,  7],
       [13, 12,  4, 12],
       [ 7, 10,  8,  6]])

In [17]:
x

array([[ 5, 12,  6,  8],
       [ 8,  5,  8,  7],
       [13, 12,  4, 12],
       [ 7, 10,  8,  6]])

In [18]:
y = x

In [19]:
y

array([[ 5, 12,  6,  8],
       [ 8,  5,  8,  7],
       [13, 12,  4, 12],
       [ 7, 10,  8,  6]])

In [20]:
y[0][0]

5

In [21]:
y

array([[ 5, 12,  6,  8],
       [ 8,  5,  8,  7],
       [13, 12,  4, 12],
       [ 7, 10,  8,  6]])

In [22]:
x

array([[ 5, 12,  6,  8],
       [ 8,  5,  8,  7],
       [13, 12,  4, 12],
       [ 7, 10,  8,  6]])

In [23]:
id(x)

140287622711120

In [24]:
id(y)

140287622711120

In [25]:
# see for copy only the memory get to change. For assigning, it shows same memory only

In [28]:
# append

In [26]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.append(x,100)

array([  5,  12,   6,   8,   8,   5,   8,   7,  13,  12,   4,  12,   7,
        10,   8,   6, 100])

In [29]:
x1=np.random.randint(12,size=(3,3))

In [30]:
x1

array([[11,  0,  5],
       [ 0,  5,  3],
       [ 8, 10,  2]])

In [31]:
np.append(x1,[[0,1,2]])

array([11,  0,  5,  0,  5,  3,  8, 10,  2,  0,  1,  2])

In [32]:
np.append(x1,[[0,1,2]],axis=0)

array([[11,  0,  5],
       [ 0,  5,  3],
       [ 8, 10,  2],
       [ 0,  1,  2]])

In [34]:
x = np.array([6,7,2,3])

In [35]:
x

array([6, 7, 2, 3])

In [36]:
y = np.array([4,10,10,5])

In [37]:
y

array([ 4, 10, 10,  5])

In [38]:
np.append(x,y)

array([ 6,  7,  2,  3,  4, 10, 10,  5])

In [39]:
x=np.arange(12).reshape(2,6)

In [40]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [41]:
x.ndim

2

In [42]:
y=np.random.randint(10,size=(3,6)) # same 6 columns is must. if not means, it shows error

In [43]:
y

array([[1, 2, 9, 7, 3, 4],
       [3, 8, 3, 4, 9, 1],
       [2, 2, 5, 0, 4, 5]])

In [44]:
np.append(x,y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2,  9,  7,  3,
        4,  3,  8,  3,  4,  9,  1,  2,  2,  5,  0,  4,  5])

In [45]:
np.append(x,y,axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 1,  2,  9,  7,  3,  4],
       [ 3,  8,  3,  4,  9,  1],
       [ 2,  2,  5,  0,  4,  5]])