# Numpy

In [1]:
import numpy as np

# random.random()

In [3]:
x = np.random.random()

In [4]:
x

0.03263296635647028

In [5]:
x = np.random.random()

In [6]:
x

0.5646360681463786

In [7]:
# Each time, it generates different random numbers

# random.randint()

In [9]:
x = np.random.randint() # it shows error, bcoz it needs one integer argument

TypeError: randint() takes at least 1 positional argument (0 given)

In [10]:
x = np.random.randint(12)

In [11]:
x

6

In [13]:
x = np.random.randint(12)

In [14]:
x

0

In [15]:
# Each time, it generates different random numbers within the range of 12

# random.randint() with size

In [16]:
x = np.random.randint(12, size = 10)

In [17]:
x

array([1, 0, 9, 7, 0, 4, 3, 5, 4, 0])

In [19]:
x = np.random.randint(12, size = 5)

In [20]:
x

array([11,  0,  1,  8,  2])

In [21]:
# Now it generates size of 10 or 5 digits within the range of 12

In [22]:
x = np.random.randint(12, size = (5,5))

In [23]:
x

array([[ 4,  5,  7,  4,  0],
       [ 7,  6, 10,  3,  8],
       [ 5,  3,  6,  2,  9],
       [ 6, 10,  8,  6,  2],
       [ 9, 11, 11,  6,  0]])

In [24]:
x.dtype

dtype('int64')

In [25]:
x.ndim

2

In [26]:
x.size

25

In [27]:
x.nbytes

200

# random.randint() with dtype

In [28]:
x = np.random.randint(12, size = (5,5), dtype = np.int8)

In [29]:
x

array([[ 0,  3,  7,  6,  0],
       [ 0,  7, 11,  8,  7],
       [ 4,  2,  5,  6,  6],
       [ 6,  3,  4,  1,  7],
       [ 8, 10,  5,  3,  8]], dtype=int8)

In [30]:
np.random.randint(120,size=(3,3))

array([[ 65,  37,  35],
       [ 18,  67,  32],
       [ 41,  40, 107]])

# Choice 

In [32]:
x=np.random.choice(np.random.randint(10))

In [33]:
x

1

In [34]:
x=np.random.choice(np.random.randint(10))

In [35]:
x

0

In [38]:
x = np.random.choice([1,2,3])

In [39]:
x

1

In [40]:
x = np.random.choice([1,2,3])

In [41]:
x

1

In [42]:
x = np.random.choice([1,2,3])

In [43]:
x

2

In [44]:
# So each time, it generates different numbers within the choice of numbers

In [45]:
x = np.random.choice(np.random.randint(12, size = 10), size = (3,3))

In [46]:
x

array([[1, 9, 9],
       [1, 7, 4],
       [1, 9, 1]])

# arange

In [47]:
x = np.arange(10) # a range of 10 (which means n-1)

In [48]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])