# NumPy Searching

# where()

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5, 4, 4])

In [3]:
x

array([1, 2, 3, 4, 5, 4, 4])

In [4]:
np.where(x == 4)

(array([3, 5, 6], dtype=int64),)

In [6]:
np.where(x%2 == 0) # even

(array([1, 3, 5, 6], dtype=int64),)

In [7]:
np.where(x%2 == 1) # odd

(array([0, 2, 4], dtype=int64),)

# searchsorted()

In [8]:
x = np.array([6,7,8,9])

In [9]:
np.searchsorted(x,7)

1

In [10]:
np.searchsorted(x,7,side = "right")

2

In [11]:
x = np.array([1,3,5,7])

In [12]:
np.searchsorted(x, [2,4,6])

array([1, 2, 3], dtype=int64)