# Numpy

# copy

In [1]:
import numpy as np

In [2]:
l=[i for i in range(10)]

In [3]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
x = np.copy(l)

In [5]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
id(l)

140421433921344

In [7]:
id(x)

140421431448080

In [8]:
x[0] = 100

In [9]:
x

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [10]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
# See it shows seperate memory location for copy. Also changes in copy is not reflected in original

In [12]:
l[1] = 1000

In [13]:
l

[0, 1000, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
x

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [15]:
# Also the changes made in original is not reflected in copy

In [16]:
# In other words, it can be said that the copy is physically stored at another location and view has the same memory location as the original array.

In [17]:
# This is also known as Deep Copy. The copy is completely a new array and copy owns the data. When we make changes to the copy it does not affect the original array, and when changes are made to the original array it does not affect the copy.

# Assinging

In [18]:
a=np.array([2,4,5,6])

In [19]:
a

array([2, 4, 5, 6])

In [20]:
b = a

In [21]:
b

array([2, 4, 5, 6])

In [22]:
id(a)

140421813478480

In [23]:
id(b)

140421813478480

In [24]:
b.base # return nothing. So it doesn't hold the data

In [25]:
a.base # return nothing. So it doesn't hold the data

In [26]:
# See for just assigning we will get same memory location. But in copy, it stores in seperate memory

In [27]:
b[0] = 100

In [28]:
b

array([100,   4,   5,   6])

In [29]:
a

array([100,   4,   5,   6])

In [30]:
# See here, changes in b reflects in a also

In [31]:
a[1] = 1000

In [32]:
a

array([ 100, 1000,    5,    6])

In [33]:
b

array([ 100, 1000,    5,    6])

In [34]:
# See here, changes in a reflects in b also

In [35]:
# this is called as shallow copy

# View

In [36]:
# The view is just a view of the original array and view does not own the data. When we make changes to the view it affects the original array, and when changes are made to the original array it affects the view.

In [37]:
i = np.array([1,2,3,5,6])

In [38]:
j = i.view()

In [39]:
j

array([1, 2, 3, 5, 6])

In [40]:
id(i)

140421813478288

In [41]:
id(j)

140421813480304

In [42]:
j[0] = 100

In [43]:
j

array([100,   2,   3,   5,   6])

In [44]:
i

array([100,   2,   3,   5,   6])

In [45]:
# See here, changes made in j reflect in i also

In [46]:
i[1] = 100

In [47]:
i

array([100, 100,   3,   5,   6])

In [48]:
j

array([100, 100,   3,   5,   6])

In [49]:
# see here, changes made in i reflect in j also

In [50]:
# NumPy array has the attribute base that returns None if the array owns the data. Else, the base attribute refers to the original object.

In [51]:
j.base # return the data. So it hold the data

array([100, 100,   3,   5,   6])

In [52]:
i.base # return nothing. So it doesn't hold the data