# Numpy

In [1]:
import numpy as np

In [2]:
x = np.empty?

In [4]:
x = np.empty((3,3)) # tuple

In [5]:
x

array([[ 3.45126646e-31, -6.90253292e-31,  1.72563323e-31],
       [-6.90253292e-31,  1.50130091e-30, -4.65920972e-31],
       [ 1.72563323e-31, -4.65920972e-31,  2.67473151e-31]])

In [6]:
x = np.empty([3,3]) # list

In [7]:
x

array([[3.45126646e-31, 6.90253292e-31, 1.72563323e-31],
       [6.90253292e-31, 1.50130091e-30, 4.65920972e-31],
       [1.72563323e-31, 4.65920972e-31, 2.67473151e-31]])

In [8]:
# To get without float

In [9]:
x = np.empty((3,3), dtype = np.int8)

In [10]:
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [11]:
x=np.random.randint(12,size=(5,5))

In [12]:
x

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [13]:
x[0]

array([4, 8, 6, 1, 9])

In [14]:
x[1]

array([ 9, 11, 11,  4,  0])

In [15]:
x[0][0]

4

In [16]:
x[0][1]

8

In [17]:
x[0:3] # 0 1 2

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4]])

In [18]:
x[:]

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [20]:
x[2:] # 2 3 4

array([[ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [21]:
# To get 0,9,10

In [22]:
x[2:,3]

array([ 0,  9, 10])

# Always before comma is row and after comma is column

In [23]:
x[2:,2:]

array([[ 3,  0,  4],
       [10,  9,  8],
       [11, 10,  7]])

In [24]:
x

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [25]:
# Indexing

In [26]:
x[0]

array([4, 8, 6, 1, 9])

In [27]:
x[1]

array([ 9, 11, 11,  4,  0])

In [28]:
# To access 0 to 4

In [29]:
x[0:4] # 0 1 2 3

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8]])

In [30]:
x[0:4,0:3]

array([[ 4,  8,  6],
       [ 9, 11, 11],
       [ 4,  1,  3],
       [ 8,  4, 10]])

In [31]:
x[:,0:3]

array([[ 4,  8,  6],
       [ 9, 11, 11],
       [ 4,  1,  3],
       [ 8,  4, 10],
       [ 6,  0, 11]])

In [32]:
x

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [33]:
x[0:3,0:3]

array([[ 4,  8,  6],
       [ 9, 11, 11],
       [ 4,  1,  3]])

# array[rowindexing,columnindexing]

In [34]:
x[3:,2:4]

array([[10,  9],
       [11, 10]])

In [50]:
a = np.arange(10)

In [51]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
slice?

In [53]:
s = slice(10) # 0 to 9

In [54]:
a[s]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
s = slice(3) # 0 1 2

In [56]:
a[s]

array([0, 1, 2])

In [59]:
a = np.arange(20)

In [60]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [61]:
s = slice(10,15) # start, stop, step

In [63]:
s

slice(10, 15, None)

In [64]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
a.ndim

1

In [66]:
a.shape

(20,)

In [67]:
a[s]

array([10, 11, 12, 13, 14])

In [68]:
s=slice(10,18,2)

In [69]:
a[s]

array([10, 12, 14, 16])

In [70]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
a[10:18:2]

array([10, 12, 14, 16])

In [72]:
x

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [73]:
x[0:6,:]

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [74]:
x[0:5,:]

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [76]:
x[:]

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [77]:
x[:,:]

array([[ 4,  8,  6,  1,  9],
       [ 9, 11, 11,  4,  0],
       [ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [78]:
x[3:,:]

array([[ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [79]:
#x[row_starting:row_ending-1 , colum_start:colum_end-1]

In [80]:
x.shape

(5, 5)

In [81]:
x[2:5]

array([[ 4,  1,  3,  0,  4],
       [ 8,  4, 10,  9,  8],
       [ 6,  0, 11, 10,  7]])

In [82]:
 x[2:5,1:3]

array([[ 1,  3],
       [ 4, 10],
       [ 0, 11]])