# Data Manipulation

# Relational operations

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
x

array([1, 2, 3, 4, 5])

In [4]:
x<3

array([ True,  True, False, False, False])

In [5]:
x>3

array([False, False, False,  True,  True])

In [6]:
x<=3

array([ True,  True,  True, False, False])

In [7]:
x>=3

array([False, False,  True,  True,  True])

In [8]:
x==3

array([False, False,  True, False, False])

In [9]:
x!=3

array([ True,  True, False,  True,  True])

In [10]:
x

array([1, 2, 3, 4, 5])

In [11]:
np.less(x,3)

array([ True,  True, False, False, False])

In [12]:
x<3 # see both are same

array([ True,  True, False, False, False])

In [13]:
np.less_equal(x,3)

array([ True,  True,  True, False, False])

In [14]:
np.equal(x,3)

array([False, False,  True, False, False])

In [15]:
np.not_equal(x,3)

array([ True,  True, False,  True,  True])

In [16]:
np.greater(x,3)

array([False, False, False,  True,  True])

In [17]:
np.greater_equal(x,3)

array([False, False,  True,  True,  True])

In [18]:
x

array([1, 2, 3, 4, 5])

In [19]:
x * 2

array([ 2,  4,  6,  8, 10])

In [20]:
 x*2 < x

array([False, False, False, False, False])

In [21]:
 x*2 <= x

array([False, False, False, False, False])

In [22]:
x*2 <= x**2

array([False,  True,  True,  True,  True])

# RandomState

In [24]:
rng=np.random.RandomState(0)

In [25]:
rng

RandomState(MT19937) at 0x7FD991B7B540

In [26]:
x

array([1, 2, 3, 4, 5])

In [27]:
x=rng.randint(10,size=(3,3))

In [28]:
x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [29]:
x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [30]:
# this generates each time different state

In [31]:
 np.less(x,3)

array([[False,  True, False],
       [False, False, False],
       [False, False,  True]])

In [32]:
x < 3

array([[False,  True, False],
       [False, False, False],
       [False, False,  True]])

In [33]:
x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

# Count_nonzero

In [34]:
np.count_nonzero(x<8) # count the non zero values less than 8

8

In [35]:
np.count_nonzero(x<6)# count the non zero values less than 6

7

In [38]:
np.sum(x<3) # less than 3 has two values(0 & 2)

2

In [41]:
np.sum(x<5,axis=1) # in each column counting the number of values less than 5 

array([2, 1, 2])

In [42]:
# 1st column -> 3  & 3 (2 values)
# 2nd column -> 0 (1 value)
# 3rd column -> 3 & 2 (2 values)

In [43]:
x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [44]:
np.sum(x>8) # greater than 8 is 9 only

1

In [45]:
np.sum(x) # this is normal sum(x)

37

In [46]:
np.sum(x>7) # greater than 7 is 9 only

1

In [48]:
x>7 # see only 9 is true

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

# Any

In [49]:
x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [50]:
np.any(x>6)

True

In [51]:
x>6 # there is 2 true

array([[False, False, False],
       [False,  True,  True],
       [False, False, False]])

In [52]:
np.sum(x>6)

2

In [53]:
 x=np.random.randint(12,size=(8,8))

In [54]:
x

array([[ 8,  5,  2,  9,  1,  8,  8,  2],
       [ 8, 11,  2,  3, 11,  1,  8,  1],
       [ 6,  1, 11,  0,  5,  8,  4,  2],
       [11,  7,  1,  7,  9,  2,  6,  2],
       [11,  2,  0,  7,  2,  5,  1,  7],
       [ 3,  8,  5,  1, 10,  3,  6,  5],
       [11,  4,  3,  8,  6,  2,  6,  5],
       [11,  9,  2,  2,  7,  5, 10, 11]])

In [55]:
np.any(x>12)

False

In [56]:
np.any(x<3)

True

In [57]:
np.any(x<0)

False

In [58]:
np.any(x<=0)

True

In [59]:
np.sum(x<=0) # how many zeros means 2

2

# all

In [60]:
x

array([[ 8,  5,  2,  9,  1,  8,  8,  2],
       [ 8, 11,  2,  3, 11,  1,  8,  1],
       [ 6,  1, 11,  0,  5,  8,  4,  2],
       [11,  7,  1,  7,  9,  2,  6,  2],
       [11,  2,  0,  7,  2,  5,  1,  7],
       [ 3,  8,  5,  1, 10,  3,  6,  5],
       [11,  4,  3,  8,  6,  2,  6,  5],
       [11,  9,  2,  2,  7,  5, 10, 11]])

In [61]:
np.all(x<10)

False

In [62]:
np.all(x<120)

True

In [63]:
np.all(x<15)

True

In [64]:
np.all(x==6)

False

In [67]:
np.all(x<3,axis=1)

array([False, False, False, False, False, False, False, False])

In [68]:
x=np.random.randint(10,size=(3,3))

In [69]:
x

array([[1, 9, 6],
       [8, 7, 4],
       [6, 9, 4]])

In [70]:
np.all(x<3,axis=1)

array([False, False, False])

In [71]:
np.any(x<3,axis=1)

array([ True, False, False])

# Fancy indexing

In [74]:
 x=np.random.randint(15,size=(5,5))

In [75]:
x

array([[ 0,  2,  5,  7, 12],
       [ 4, 12,  3,  2, 13],
       [ 5, 11,  1, 13,  7],
       [ 3,  6, 12, 13, 10],
       [ 2,  2,  7,  4,  8]])

In [76]:
x<5

array([[ True,  True, False, False, False],
       [ True, False,  True,  True, False],
       [False, False,  True, False, False],
       [ True, False, False, False, False],
       [ True,  True, False,  True, False]])

In [77]:
x[x<5] # it shows true values alone in x

array([0, 2, 4, 3, 2, 1, 3, 2, 2, 4])

In [78]:
 x=np.random.randint(12,size=10)

In [79]:
x

array([10,  6,  6,  7,  2,  9,  8,  1,  0, 11])

In [80]:
x[3]

7

In [81]:
x[0]

10

In [83]:
x[1]

6

In [82]:
 x[3],x[0],x[1] # it shows in tuple

(7, 10, 6)

In [84]:
[x[3],x[0],x[1]] 

[7, 10, 6]

In [85]:
ix=[3,0,1]

In [87]:
x[ix]

array([ 7, 10,  6])

In [88]:
# fancy indexing the shape of the result reflect the shape of array

In [89]:
 ix=np.array([[0,1,2],[9,8,7],[0,0,0]])

In [90]:
ix

array([[0, 1, 2],
       [9, 8, 7],
       [0, 0, 0]])

In [91]:
x[ix]

array([[10,  6,  6],
       [11,  0,  1],
       [10, 10, 10]])

In [92]:
x=np.arange(12).reshape((3,4))

In [93]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
row=np.array([0,1,2])

In [95]:
col=np.array([2,1,3])

In [96]:
x[row,col]

array([ 2,  5, 11])

In [97]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
 x[2,[2,0,1]] # 2nd row and 2nd column 0th column and 1st column values

array([10,  8,  9])

In [99]:
x[1:,[2,0,1]] # After 1st row all values and same like before 

array([[ 6,  4,  5],
       [10,  8,  9]])

In [100]:
x=np.arange(10)

In [101]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
i=np.array([2,1,8,4])

In [103]:
x[i]

array([2, 1, 8, 4])

In [104]:
i=np.array([2,1,8,4])

In [105]:
x[i] = 99

In [106]:
x

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])