# Numpy

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4]) # list

In [3]:
x

array([1, 2, 3, 4])

In [4]:
x = np.array((5,6,7,8)) # tuple

In [5]:
x

array([5, 6, 7, 8])

In [6]:
l = [i for i in range(10)]

In [7]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
x = np.array(l) # Now we are getting numpy methods(more methods)

In [10]:
x.max()

9

In [11]:
x.min()

0

In [12]:
x.mean()

4.5

In [13]:
x.dtype

dtype('int64')

In [14]:
x.ndim

1

In [15]:
x.size

10

In [16]:
x.itemsize

8

In [17]:
x.nbytes

80

In [18]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x = np.array([0,1,2,3,4,5,6,7,8,9])

In [21]:
x.dtype

dtype('int64')

In [22]:
x = np.array?

In [ ]:
x = np.array

In [23]:
x = np.array([0,1,2,3,4,5,6,7,8,9], dtype = np.int8)

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [25]:
x.dtype

dtype('int8')

In [26]:
x.ndim

1

In [29]:
x.size

10

In [31]:
# itemsize ---> memory (bytes) for single element in an array
# nbytes ---> memory bytes for all the elements of array
# size  ---> number of elements in the array
# ndim  ----> number of dimensions in the array
# dtype ----> data type of an array

# Ones

In [32]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones((3,3), dtype = 'int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
x=np.ones((10,10),dtype='int8')

In [38]:
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [39]:
x.ndim

2

# arange

In [40]:
x = np.arange(20) 

In [41]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
x.ndim

1

In [43]:
x.size

20

In [44]:
x.dtype

dtype('int64')

In [47]:
x.itemsize

8

In [48]:
x.nbytes

160

In [50]:
x = np.arange(20).reshape(5,4)

In [51]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [52]:
x = np.arange(20).reshape(4,5)

In [53]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
x.ndim

2

In [55]:
x.T # Transform

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Attributes of numpy

In [56]:
x = np.array({"Numbers":[1,2,3,4,5]}) # Dict

In [57]:
x

array({'Numbers': [1, 2, 3, 4, 5]}, dtype=object)

In [58]:
x.shape # we didn't get a shape

()

In [59]:
x = np.array((1,2,3))

In [61]:
x.shape

(3,)

In [62]:
# See for dict-we are not getting the shape
# But for tuple we are getting the shape bcoz dict having keys and values

In [63]:
x = np.ones?

In [ ]:
x = np.ones

In [64]:
# C is row (C-Style)
# F is column ((Fortran-style))

# In default C is used

In [65]:
x = np.ones((4,4), dtype = np.int8, order = 'F')

In [66]:
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [67]:
x = np.ones((4,4), dtype = np.int8)

In [68]:
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [69]:
# So giving order is optional

In [70]:
x = np.zeros(10)

In [71]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
type(x)

numpy.ndarray

In [73]:
x.dtype

dtype('float64')

In [74]:
x.ndim

1

In [75]:
x.size

10

In [76]:
x.itemsize

8

In [77]:
x.nbytes

80

In [78]:
x.shape

(10,)

In [79]:
x.data?

In [80]:
x.data

# full in numpy

In [81]:
x = np.full((3,3),fill_value=10)

In [82]:
x

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Array creation methods

In [83]:
x = np.linspace?

In [84]:
x = np.linspace(0,5,5)

In [85]:
x

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [86]:
x = np.linspace(0,5,5,dtype = np.int8)

In [87]:
x

array([0, 1, 2, 3, 5], dtype=int8)

In [88]:
x=np.linspace(1234,5,5,dtype=np.int16)

In [89]:
x

array([1234,  926,  619,  312,    5], dtype=int16)