# Numpy

# axis

In [1]:
import numpy as np

In [2]:
data = np.array([[1,2,3,4],[5,6,7,8],[9,2,4,5],[4,6,8,3]])

In [3]:
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 2, 4, 5],
       [4, 6, 8, 3]])

In [4]:
data.ndim

2

In [5]:
data.max() # it returns the maximum value of each column

9

In [6]:
data.max(axis = 0) # it returns the maximum value of each column

array([9, 6, 8, 8])

In [7]:
data.max(axis = 1) # it returns the maximum value of each row

array([4, 8, 9, 8])

In [8]:
# if didn't give give any axis means, it will return max value of column only

# reshape

In [9]:
x = np.arange(12)

In [10]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
x.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
x.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
x.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

# hstack

In [15]:
x = np.array([1,2,3])

In [16]:
y = np.array([4,5,6])

In [17]:
np.hstack?

In [18]:
np.hstack((x,y)) # it accepts only in tuple

array([1, 2, 3, 4, 5, 6])

In [19]:
x.ndim

1

In [30]:
x1 = np.array([[1,2,3],[4,5,6]])

In [31]:
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
y1 = np.array([[1,2,3],[4,5,6]])

In [33]:
y1

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.hstack((x1,y1)) # it is horizontally combine the matrix(row-wise)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [23]:
a=np.random.randint(20,size=(3,3))

In [24]:
b=np.random.randint(20,size=(3,3))

In [25]:
a

array([[ 7,  2,  7],
       [ 4, 12,  8],
       [ 2,  7, 16]])

In [26]:
b

array([[ 8, 11, 15],
       [17, 16, 19],
       [17, 13, 15]])

In [28]:
np.stack((a,b)) # this is normal stack

array([[[ 7,  2,  7],
        [ 4, 12,  8],
        [ 2,  7, 16]],

       [[ 8, 11, 15],
        [17, 16, 19],
        [17, 13, 15]]])

In [29]:
np.hstack((a,b)) # it horizontally combine the matrix in row-wise

array([[ 7,  2,  7,  8, 11, 15],
       [ 4, 12,  8, 17, 16, 19],
       [ 2,  7, 16, 17, 13, 15]])

# vstack

In [35]:
a

array([[ 7,  2,  7],
       [ 4, 12,  8],
       [ 2,  7, 16]])

In [36]:
b

array([[ 8, 11, 15],
       [17, 16, 19],
       [17, 13, 15]])

In [37]:
np.vstack((a,b))

array([[ 7,  2,  7],
       [ 4, 12,  8],
       [ 2,  7, 16],
       [ 8, 11, 15],
       [17, 16, 19],
       [17, 13, 15]])

# block

In [38]:
a=np.array([1,2,3])

In [39]:
b=np.array([1,2,3])

In [40]:
c=np.array([1,2,3])

In [43]:
np.block([a,b,c]) # this is also same as stack

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [44]:
a=np.random.randint(20,size=(3,3))

In [45]:
b=np.random.randint(20,size=(3,3))

In [46]:
a

array([[17,  1,  7],
       [ 1, 12, 15],
       [ 3, 15,  9]])

In [47]:
b

array([[ 2,  5,  3],
       [18, 12,  5],
       [10, 15,  4]])

In [48]:
np.block([a,b]) 

array([[17,  1,  7,  2,  5,  3],
       [ 1, 12, 15, 18, 12,  5],
       [ 3, 15,  9, 10, 15,  4]])

# concatenate

In [50]:
a = np.array([[4,8],[6,1]])

In [53]:
a

array([[4, 8],
       [6, 1]])

In [51]:
b = np.array([[3,5],[7,2]])

In [54]:
b

array([[3, 5],
       [7, 2]])

In [55]:
np.hstack((a,b)) # row-wise

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [56]:
np.vstack((a,b)) # column-wise

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [57]:
np.concatenate((a,b)) # defaultly it is column-wise

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [58]:
np.concatenate((a, b), axis=None)

array([4, 8, 6, 1, 3, 5, 7, 2])

In [59]:
np.concatenate((a, b), axis=0) # axis = 0 means column-wise

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [60]:
np.concatenate((a, b), axis=1) # axis = 1 means row-wise

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [61]:
# concatenate is also similar to hstack and vstack. Based on axis, we can change the matrix

# pandas intro

In [62]:
import pandas as pd

In [64]:
data = pd.Series(np.random.randint(12,size = 10))

In [65]:
data

0    10
1     4
2     1
3     3
4     6
5     2
6     2
7     9
8     8
9     4
dtype: int64

In [66]:
data.ndim

1

In [67]:
a1 = pd.Series(np.random.randint(12,size = 5))

In [68]:
 b1 = pd.Series(np.random.randint(12,size = 5))

In [69]:
data = pd.DataFrame({"Math":a1,"Science":b1})


In [70]:
data

Math  Science
0    11       11
1     5        1
2    10        0
3    10        3
4     6        8

In [72]:
data.ndim

2