# Numpy

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

In [4]:
y = np.array([4,5,6])

In [5]:
y

array([4, 5, 6])

In [6]:
res = x < y

In [7]:
res

array([ True,  True,  True])

In [8]:
res1 = x > y

In [9]:
res1

array([False, False, False])

In [10]:
x = np.random.randint(12, size = (3,3))

In [11]:
x

array([[ 7, 10, 10],
       [ 3,  3,  4],
       [ 0,  6,  4]])

In [13]:
y = np.random.randint(12, size = (3,3))

In [14]:
y

array([[ 0,  1,  0],
       [ 2,  3,  7],
       [ 4, 11,  5]])

In [15]:
x < y

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [16]:
x == y

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [17]:
x != y

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

# Above comparison operators are basic python operations. Now we can see numpy operations using its default methods

In [20]:
x

array([[ 7, 10, 10],
       [ 3,  3,  4],
       [ 0,  6,  4]])

In [21]:
y

array([[ 0,  1,  0],
       [ 2,  3,  7],
       [ 4, 11,  5]])

In [18]:
np.less(x,y) # lesser(<)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [19]:
np.greater(x,y) # greater(>)

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [22]:
np.less_equal(x,y) # less than or equalto(<=)

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [23]:
np.greater_equal(x,y) # greater than or equalto(>=)

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [24]:
np.equal(x,y) # equal to (==)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [25]:
np.not_equal(x,y) # not equal to(!=)

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

# Logical Operations

In [26]:
x = np.array([True,False,True])

In [27]:
y = np.array([False,False,True])

In [28]:
x

array([ True, False,  True])

In [29]:
y

array([False, False,  True])

In [31]:
np.logical_and(x,y)

array([False, False,  True])

In [32]:
np.logical_or(x,y)

array([ True, False,  True])

In [33]:
np.logical_not(x,y)

array([False,  True, False])

In [34]:
np.logical_not(x)

array([False,  True, False])

In [35]:
np.logical_not(y)

array([ True, False,  True])

In [36]:
np.logical_xor(x,y)

array([ True,  True,  True])