# Numpy spliting

In [9]:
import numpy as np

In [12]:
np.array_split?

In [19]:
x = np.arange(10)

In [20]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.array_split(x, 3) # which means split into 3 arrays

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [22]:
x = np.arange(8.0)

In [23]:
x

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [24]:
np.array_split(x,4) # which means split into 4 arrays

[array([0., 1.]), array([2., 3.]), array([4., 5.]), array([6., 7.])]

In [25]:
# Splitting 2-D Arrays

In [28]:
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

In [30]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
np.array_split(x,3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [32]:
newarr = np.array_split(x, 3, axis=1) # column-wise

In [33]:
newarr

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]]),
 array([], shape=(6, 0), dtype=int32)]

In [35]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

In [36]:
newarr = np.hsplit(y, 3) # same like axis=1

In [37]:
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]