# Numpy Aggregation

# reduce

In [1]:
import numpy as np

In [4]:
x = np.arange(1,6)

In [5]:
x

array([1, 2, 3, 4, 5])

In [6]:
np.add.reduce(x) # this is adding all the values in x

15

In [7]:
np.sum(x) # see both are giving same answer

15

In [8]:
x

array([1, 2, 3, 4, 5])

In [9]:
np.multiply.reduce(x) # this is multiplying all the values of x

120

# accumulate

In [13]:
x = np.arange(1,6)

In [14]:
x

array([1, 2, 3, 4, 5])

In [15]:
np.add.accumulate(x) # 1+1=1, 1+2=3, 1+2+3=6, 1+2+3+4=10, 1+2+3+4+5=15

array([ 1,  3,  6, 10, 15])

# Some of the aggregate functions

In [16]:
x=np.random.random((3,4))

In [17]:
x

array([[0.87536543, 0.81852478, 0.46109703, 0.70180661],
       [0.6947957 , 0.77259869, 0.13437307, 0.087288  ],
       [0.7539316 , 0.2407619 , 0.68661049, 0.86021299]])

In [18]:
x.sum()

7.0873663000419

In [19]:
x.min()

0.08728799766904771

In [20]:
x.max()

0.8753654265338743

In [21]:
x.min(axis = 0) # take the min of column values

array([0.6947957 , 0.2407619 , 0.13437307, 0.087288  ])

In [22]:
x.min(axis=1) # take the min of row values

array([0.46109703, 0.087288  , 0.2407619 ])

In [23]:
x=np.array([[0,10,20],[30,40,50],[60,70,80]])

In [24]:
x

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [25]:
x.sum()

360

In [26]:
np.sum(x) # both are same

360

In [27]:
x.sum(axis = 0) # sum of each column

array([ 90, 120, 150])

In [28]:
x.sum(axis=1) # sum of each row

array([ 30, 120, 210])

In [29]:
# average and mean are same

In [30]:
np.average?

In [31]:
x

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [32]:
x.sum(0) # this is also called axis = 0(column)

array([ 90, 120, 150])

In [33]:
x.sum(1) # this is also called axis = 1(row)

array([ 30, 120, 210])

In [34]:
np.average(x)

40.0

In [35]:
np.sum(x)

360

In [36]:
np.sum(x)/9

40.0

In [37]:
np.mean(x) # see avg and mean are giving the same answer(both are same)

40.0

In [38]:
x

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [39]:
np.average(0)

0.0

In [40]:
np.average(x,axis=0) # average of each column

array([30., 40., 50.])

In [41]:
np.average(x,axis=1) # average of each row

array([10., 40., 70.])

In [44]:
# average explanation

In [47]:
(0+30+60)/3

30.0

In [48]:
(10+40+70)/3

40.0

In [49]:
(20+50+80)/3

50.0

In [50]:
(0+10+20)/3

10.0

In [51]:
(30+40+50)/3

40.0

In [52]:
(60+70+80)/3

70.0

In [53]:
np.mean(x, axis = 0)

array([30., 40., 50.])

In [54]:
np.mean(x, axis = 1)

array([10., 40., 70.])

In [55]:
x

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [56]:
np.min(x)

0

In [57]:
np.max(x)

80

In [58]:
np.min(x,axis=0) # min of each column

array([ 0, 10, 20])

In [59]:
np.min(x,axis=1) # min of each row

array([ 0, 30, 60])

In [60]:
x.min(axis=0)

array([ 0, 10, 20])

In [61]:
x.min(axis=1) # both are same

array([ 0, 30, 60])

In [62]:
np.min?

In [63]:
x=np.random.randint(1,10,size=(5,5))

In [64]:
x

array([[3, 4, 1, 8, 9],
       [9, 5, 9, 3, 2],
       [2, 4, 4, 8, 8],
       [8, 2, 8, 1, 2],
       [5, 6, 7, 5, 3]])

In [65]:
y=np.random.randint(1,10,size=(5,5))

In [66]:
y

array([[9, 1, 9, 9, 8],
       [2, 4, 5, 2, 7],
       [4, 2, 4, 8, 6],
       [8, 3, 4, 6, 2],
       [4, 6, 5, 6, 6]])

In [67]:
np.minimum?

In [68]:
# in minimum function, need to give two axes(x1,x2)

In [69]:
np.minimum(x,y)

array([[3, 1, 1, 8, 8],
       [2, 4, 5, 2, 2],
       [2, 2, 4, 8, 6],
       [8, 2, 4, 1, 2],
       [4, 6, 5, 5, 3]])

In [70]:
np.maximum(x,y)

array([[9, 4, 9, 9, 9],
       [9, 5, 9, 3, 7],
       [4, 4, 4, 8, 8],
       [8, 3, 8, 6, 2],
       [5, 6, 7, 6, 6]])

In [71]:
x = np.random.randint(12,size = (2,4))

In [72]:
x

array([[11,  1,  0,  9],
       [ 8,  4,  1,  1]])

In [73]:
y = np.random.randint(12,size = (2,4))

In [74]:
y

array([[ 4,  9,  4, 11],
       [ 2,  5,  5,  7]])

In [79]:
# minimum and maximum 

In [75]:
x

array([[11,  1,  0,  9],
       [ 8,  4,  1,  1]])

In [76]:
y

array([[ 4,  9,  4, 11],
       [ 2,  5,  5,  7]])

In [77]:
np.maximum(x,y)  # it compares with each value of same place in matrix

array([[11,  9,  4, 11],
       [ 8,  5,  5,  7]])

In [78]:
np.minimum(x,y)

array([[4, 1, 0, 9],
       [2, 4, 1, 1]])